name: sa7ten
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  image: images/Sa7ten.png    # Path to your placeholder image
  android: true               # Enable for Android
  ios: true
  color: "#ffffff"            # Specify a background color
  android_gravity: fill       # Ensure the image fills the screen on Android
  ios_content_mode: scaleAspectFill # Ensure the image fills the screen on iOS

flutter:
  uses-material-design: true

  assets:
    - images/Sa7ten.gif
    - images/Sa7ten.png
    - images/try.png